### ISSUE TITLE
Setup the main network for Opet - Initial Setup

### ISSUE THREAD

**Issue by Burmenska** [opetfoundation/eco_blockchain#17]
Develop the configuration files to describe (Fabric configs) and run (docker compose configs) the main network.

Definition of done:

- Fabric and docker compose configuration files are done

Acceptance criteria:

- Code review of the changes is approved

**Comment by Burmenska** [comment]
@serebrov  , what will be shown on Sprint Demo? if it is some screen capture - please attach it here. Much thanx

**Comment by serebrov** [comment]
@Burmenska as we discussed, for now we can only show the code -https://github.com/opetfoundation/eco_blockchain/pull/30/files
And I can explain what is what

**Comment by Burmenska** [comment]
@serebrov   ok, perfect :)
