### ISSUE TITLE
Communicate with peer chaincode from API

### ISSUE THREAD

**Issue by Burmenska** [opetfoundation/eco_blockchain#23]
Subtask for #19

As an API developer, I want to be able to communicate with Hyperledger peer chaincode to perform network transactions.

Definition of Done:
- ability to invoke chaincode from API

Acceptance criteria:
- chaincode can be invoked from API

**Comment by Norfolks** [comment]
https://github.com/opetfoundation/eco_blockchain/pull/29/files
